DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.urls import path

from django.urls import include
from django.contrib import admin
admin.autodiscover()

from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/profile/', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('links/', views.links, name='links'),
    path('about/', views.about, name='about'),
    path('anketa/', views.anketa, name='anketa'),
    path('pool/', views.pool, name='pool'),
    path('video/', views.video, name='video'),
    path('blog/', views.blog, name='blog'),
    path('newpost/', views.newpost, name='newpost'),
    path('(?P<parametr>\d+)/', views.blogpost, name='blogpost'),
    path('registration/', views.registration, name='registration'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Вход',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class AnketaForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length = 2, max_length = 100)
    city = forms.CharField(label='Ваш город', min_length = 2, max_length = 100)
    job = forms.CharField(label='Ваш вид деятельности', min_length = 2, max_length = 100)
    gender = forms.ChoiceField(label='Ваш пол',
                             choices=[('1','Мужской'),('2','Женский')],
                             widget=forms.RadioSelect, initial=1)
    internet = forms.ChoiceField(label='Как часто вы пользуетесь интернетом',
                             choices=[('1','Каждый день'),('2','Несколько раз в день'),
                                      ('3','Несколько раз в неделю'),('4','Несколько раз в месяц')],initial=1)
    notice = forms.BooleanField(label='Хотели бы вы получать новости с сайта на e-mail', required=False)
    email = forms.EmailField(label='Ваш e-mail', min_length = 7)
    message = forms.CharField(label='Коротко о себе',
                              widget=forms.Textarea(attrs={'rows':12,'cols':20}))

class PoolForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length = 2, max_length = 100)
    email = forms.EmailField(label='Ваш e-mail', min_length = 7)
    receiver = forms.ChoiceField(label='Получатель',
                             choices=[('1','Отдел маркетинга'),('2','Отдел инженерии')],
                             widget=forms.RadioSelect, initial=1)
    theme = forms.CharField(label='Тема', min_length = 2, max_length = 100)
    message = forms.CharField(label='Подробное описание',
                              widget=forms.Textarea(attrs={'rows':12,'cols':20}))
    score = forms.ChoiceField(label='Общая оценка работы сайта',
                             choices=[('1','Отлично'),('2','Хорошо'),
                                      ('3','Плохо')],initial=1)
    agree = forms.BooleanField(label='Я согласен на отправку моего вопроса', required=True)

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': "Комментарий"}

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description','content','image')
        labels = {'title': "Заголовок",'description': "Краткое содержание",'content': "Полное содержание",'image': "Изображение"}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Наша компания предоставляет услуги в сфере продажи, настройки и ремонта персональных компьютеров, ноутбуков, а также всех периферийных устройств. Наша компания предоставляет полную гарантию на все товары и услуги.</p>

{% endblock %}

app/templates/app/anketa.html
{% extends "app/layout.html" %}

{% block content %}
{% if form != None %}

<br /><h2>Отправьте, пожалуйста, заполененную анкету</h2>
<div>
    <form method="post">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }}<br />
        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}:</label>
        {{ form.city }}<br />
        <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
        {{ form.gender }}<br />
        <label for="{{ form.job.id_for_label }}">{{ form.job.label }}:</label>
        {{ form.job }}<br />
        <label for="{{ form.internet.id_for_label }}">{{ form.internet.label }}:</label>
        {{ form.internet }}<br />
        <label for="{{ form.notice.id_for_label }}">{{ form.notice.label }}:</label>
        {{ form.notice }}<br />
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }}<br />
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label>
        {{ form.message }}<br />
        <input type="submit" value="Отправить" />
    </form>
</div>
{% else %}
<br /><h2>Благодарим за предоставленнную информацию о себе!</h2>
<h3>Вы сообщили о себе следующее:</h3>
<ul>
    <li><span>Имя:</span>{{ data.name }}</li>
    <li><span>Город:</span>{{ data.city }}</li>
    <li><span>Пол:</span>{{ data.gender }}</li>
    <li><span>Вид деятельности:</span>{{ data.job }}</li>
    <li><span>В интернете:</span>{{ data.internet }}</li>
    <li><span>Получать новости с сайта:</span>{{ data.notice }}</li>
    <li><span>Ваш e-mail:</span>{{ data.email }}</li>
    <li><span>Информация о себе:</span>{{ data.message }}</li>
</ul>
{% endif %}
{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>

{% for post in posts %}
<br />
<div class="media">
    <div class="media-body">
        <h2>{{ post.title }}</h2>
        <h4>{{ post.posted }}</h4>
        <p>{{ post.description }}</p>
        <p>Автор:{{ post.author }}</p>
        <p><a href="{% url 'blogpost' parametr=post.id %}" class="btn btn-primary btn-large">Читать далее</a></p>
    </div>
</div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<div class="media">
    <div class="media-body">
        <h2>{{ post_1.title }}</h2>
        {% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
        <img src="{{post_1.image.url }}" alt="Изображение" widht="300" height="200" />
        {% endif %}
        <p>{{ post_1.content|linebreaksbr }}</p>
        <p>Автор:{{ post.author }}</p>
        <p><a href="{% url 'blog' %}" class="btn btn-primary btn-large">Назад</a></p><br />
    </div>
</div>
<div class="media">
    <div class="media-body">
        {% for comment in comments %}
        <br />
        <h3>Пользователь {{ comment.author }} оставил комментарий</h3>
        <h4>{{ comment.text|linebreaksbr }}</h4>
        <h7>Дата{{ comment.date }}</h7>
        {% endfor %}
    </div>
</div>
<div class="media">
    <div class="media-body">
        {% if user.is_authenticated %}
        <h3>Добавить комментарий</h3>
        <form method="POST">
            {% csrf_token %}
            <div>
                {{form.as_p}}
                <button type="submit" class="btn btn-primary btn-large">Отправить</button>
            </div>
        </form>
        {% else %}
        <h3>Для добавления комменатария нужно авторизироваться</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Октябрьский проспект, 54<br />
    Псков, Россия<br />
    Номер телефона: +7(964)313-48-97
</address>

<address>
    <strong>Техническая поддержка:</strong>   <a href="mailto:cyber-service@gmail.com">cyber-service@gmail.com</a><br />
    <strong>Главный инженер:</strong>   <a href="https://vk.com/cybersamurai91">Роман Самигулин</a>
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<div class="jumbotron">
    <h1>Cyber Service</h1>
    <p class="lead">Наша компания предоставляет услуги по ремонту смартфонов, персональных компьютеров, ноутбуков и перефирии.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Узнать больше &raquo;</a></p>
</div>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/banner1.jpg'%} " alt="Первый слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p> Мы всегда готовы к вашему визиту</p>
                <p><a class="btn btn-default" href="https://www.instagram.com/p/CGss3wZDUEs/">Читать далее</a></p>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/banner2.jpg'%}" alt="Второй слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>Если вы владелец Samsung, вас ждут скидки</p>
                <p><a class="btn btn-default" href="https://www.instagram.com/p/CGAyrnBDu6z/">Читать далее</a></p>
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banner3.jpg'%} " alt="Третий слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>Чиним абсолютно любые устройства</p>
                <p><a class="btn btn-default" href="https://www.instagram.com/p/CEhYqX6jO8k/">Читать далее</a></p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Почему именно Cyber Service</h2>
        <p>
            • На рынке с 2013 года<br />
			• Высококвалифицированные сотрудники<br />
			• Гарантия на все услуги и товары от нашего магазина<br />
			• Бесплатный выезд и последующая консультация
        </p>
        <p><a class="btn btn-default" href="https://djangobook.com/django-tutorials/">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Цены</h2>
        <p>Все цены на услуги и товары формируются по нижнему порогу коммерческой ценовой политики в данном регионе. Конечная стоимость услуги будет сформирована только после полного оговаривания всех нюансов. Консультация специалиста - бесплатная.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Видимость</h2>
        <p>Вы можете следить за нашей проделанной нами рабой в социальных сетях.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Узнать больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'app/content/logo.png' %}" width="40px" alt="logo" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'video' %}">Видео</a></li>
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Новая статья</a></li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Cyber Service</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    <strong>Наши социальные сети:</strong><br />
    <a href="https://vk.com/cybersamurai91"><img src="{% static 'app/content/vk.jpg' %}" width="50px" alt="Вконтакте" /></a>
    <a href="https://www.instagram.com/strseryi/"><img src="{% static 'app/content/instagram.jpg' %}" width="50px" alt="Инстаграм" /></a>
</address>

{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Воспользуйтесь вашими данными, чтобы войти.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Пользователь</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="Далее" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите коректные имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Здравствуйте {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выход</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<div class="media">
    <div class="media-body">
        <h3>Добавить статью</h3>
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div>
                {{ blogform.as_p }}
                <button type="submit" class="save btn btn-default">Сохранить статью</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/pool.html
{% extends "app/layout.html" %}

{% block content %}
{% if form != None %}

<h2>{{ title }}.</h2>

<br /><h3>Уважаемые посетители! Данная форма предназначена для ваших вопросов.</h3>
<div>
    <form method="post">
        {% csrf_token %}
        <label id="t1" for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }}<br />
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }}<br />
        <label for="{{ form.receiver.id_for_label }}">{{ form.receiver.label }}:</label>
        {{ form.receiver }}<br />
        <label for="{{ form.theme.id_for_label }}">{{ form.theme.label }}:</label>
        {{ form.theme }}<br />
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label>
        {{ form.message }}<br />
        <label for="{{ form.score.id_for_label }}">{{ form.score.label }}:</label>
        {{ form.score }}<br />
        <label for="{{ form.agree.id_for_label }}">{{ form.agree.label }}:</label>
        {{ form.agree }}<br />
        <input id="b1" type="submit" value="Отправить" />
    </form>
    <script>
        function b1_colorin(){$('#b1').css('color', 'grey');}
        function b1_colorout(){$('#b1').css('color', 'black');}
        $('#b1').mouseover(b1_colorin);
        $('#b1').mouseout(b1_colorout);
    </script>
    <script>
        function textclick(){$('#id_name').css('background-color', 'grey');}
        function textclickoff(){$('#id_name').css('background-color', 'white');}
        $('#id_name').focus(textclick);
        $('#id_name').blur(textclickoff);
    </script>
    <script>
        function textclick(){$('#id_email').css('background-color', 'grey');}
        function textclickoff(){$('#id_email').css('background-color', 'white');}
        $('#id_email').focus(textclick);
        $('#id_email').blur(textclickoff);
    </script>
    <script>
        function textclick(){$('#id_theme').css('background-color', 'grey');}
        function textclickoff(){$('#id_theme').css('background-color', 'white');}
        $('#id_theme').focus(textclick);
        $('#id_theme').blur(textclickoff);
    </script>
    <script>
        function textclick(){$('#id_message').css('background-color', 'grey');}
        function textclickoff(){$('#id_message').css('background-color', 'white');}
        $('#id_message').focus(textclick);
        $('#id_message').blur(textclickoff);
    </script>
</div>
{% else %}
<br /><h2>Благодарим за вопрос!</h2>
<h3>Вы сообщили о себе следующее:</h3>
<ul>
    <li><span>Ваше имя:</span>{{ data.name }}</li>
    <li><span>Ваш e-mail:</span>{{ data.email }}</li>
    <li><span>Получатель:</span>{{ data.receiver }}</li>
    <li><span>Тема:</span>{{ data.theme }}</li>
    <li><span>Подробное описание:</span>{{ data.message }}</li>
    <li><span>Общая оценка работы сайта:</span>{{ data.score }}</li>
    <li><span>Я согласен на отправление моего вопроса</span>{{ data.agree }}</li>
</ul>
{% endif %}
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя.</h2>

    <form method="POST"> {% csrf_token %}
    <div>
        {{ regform.as_p }}
        <button type="submit" class="save btn btn-default">Зарегистрировать</button>
    </div>
    </form>

{% endblock %}

app/templates/app/video.html
{% extends "app/layout.html" %}

{% block content %}


<div class="media">
    <div class="media-body">
        <h1>Обзор на новые Iphone 12 Pro</h1>
        <h2>Скоро будем производить ремонт данных аппаратов</h2>
        <video src="/media/iphone12pro.mp4"
               controls="controls"
               width="800" height="450"
               poster="/media/iphone12pro.jpg"></video>
    </div>
</div>

{% endblock %}